/**
 * Catalog access helpers. The catalog manifest is generated by sync into
 * src/data/catalog.json and imported directly (build-time JSON import).
 *
 * Import from "@lib/catalog".
 */
import catalogJson from "../data/catalog.json";
import type { Catalog, CatalogDomain, CatalogGroup } from "./types";

export const catalog = catalogJson as Catalog;

/** All domains (authored + coming-soon). */
export function getDomains(): CatalogDomain[] {
  return catalog.domains;
}

/** Only domains that have authored content. */
export function getAuthoredDomains(): CatalogDomain[] {
  return catalog.domains.filter((d) => d.authored);
}

/** Find a single domain by slug. */
export function getDomain(slug: string): CatalogDomain | undefined {
  return catalog.domains.find((d) => d.slug === slug);
}

/** Find a group within a domain by its key. */
export function getGroup(
  domainSlug: string,
  groupKey: string,
): CatalogGroup | undefined {
  return getDomain(domainSlug)?.groups.find((g) => g.key === groupKey);
}

/** Flat list of {domain, slug} pairs for every authored subtopic (getStaticPaths). */
export function getAllSubtopicRefs(): { domain: string; slug: string }[] {
  const out: { domain: string; slug: string }[] = [];
  for (const d of getAuthoredDomains()) {
    for (const g of d.groups) {
      for (const s of g.subtopics) out.push({ domain: d.slug, slug: s.slug });
    }
  }
  return out;
}
