/**
 * Catalog access helpers. The catalog manifest is generated by sync into
 * src/data/catalog.json and imported directly (build-time JSON import).
 *
 * Import from "@lib/catalog".
 */
import catalogJson from "../data/catalog.json";
import type {
  Catalog,
  CatalogDomain,
  CatalogGroup,
  CatalogSubtopic,
} from "./types";

export const catalog = catalogJson as Catalog;

/** All domains (authored + coming-soon). */
export function getDomains(): CatalogDomain[] {
  return catalog.domains;
}

/** Only domains that have authored content. */
export function getAuthoredDomains(): CatalogDomain[] {
  return catalog.domains.filter((d) => d.authored);
}

/** Find a single domain by slug. */
export function getDomain(slug: string): CatalogDomain | undefined {
  return catalog.domains.find((d) => d.slug === slug);
}

/** Find a group within a domain by its key. */
export function getGroup(
  domainSlug: string,
  groupKey: string,
): CatalogGroup | undefined {
  return getDomain(domainSlug)?.groups.find((g) => g.key === groupKey);
}

/** Flat list of {domain, slug} pairs for every authored subtopic (getStaticPaths). */
export function getAllSubtopicRefs(): { domain: string; slug: string }[] {
  const out: { domain: string; slug: string }[] = [];
  for (const d of getAuthoredDomains()) {
    for (const g of d.groups) {
      for (const s of g.subtopics) out.push({ domain: d.slug, slug: s.slug });
    }
  }
  return out;
}

/** One entry in a domain's ordered learning sequence. */
export interface DomainSequenceEntry {
  group: CatalogGroup;
  subtopic: CatalogSubtopic;
}

/**
 * A domain's subtopics in learning/display order: groups in catalog order,
 * subtopics by 1-based `position` within each group. (catalog.json already
 * stores them in README order; the sort is defensive.)
 */
export function getDomainSequence(domainSlug: string): DomainSequenceEntry[] {
  const d = getDomain(domainSlug);
  if (!d) return [];
  const out: DomainSequenceEntry[] = [];
  for (const g of d.groups) {
    const subs = [...g.subtopics].sort((a, b) => a.position - b.position);
    for (const s of subs) out.push({ group: g, subtopic: s });
  }
  return out;
}

/**
 * Previous/next subtopic in the domain's learning order, CROSSING group
 * boundaries (e.g. system-design core → advanced → aws). undefined at the ends.
 */
export function getAdjacentSubtopics(
  domainSlug: string,
  slug: string,
): { prev?: DomainSequenceEntry; next?: DomainSequenceEntry } {
  const seq = getDomainSequence(domainSlug);
  const i = seq.findIndex((e) => e.subtopic.slug === slug);
  if (i < 0) return {};
  return { prev: seq[i - 1], next: seq[i + 1] };
}
