/**
 * Astro content collections (Astro 5 API — config lives at src/content.config.ts).
 *
 * The `concepts` collection is generated by scripts/sync-content.mjs into
 * src/content/concepts/<domain>/<slug>.md with prepended frontmatter. Each entry
 * id is "<domain>/<slug>". Study pages do:
 *
 *   import { getCollection, getEntry } from "astro:content";
 *   const entry = await getEntry("concepts", `${domain}/${slug}`);
 *   const { Content, headings } = await render(entry);   // render() from astro:content
 */
import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const concepts = defineCollection({
  loader: glob({
    pattern: "**/*.md",
    base: "./src/content/concepts",
    // Entry id === "<domain>/<slug>" (path without extension), so entries are
    // unique across domains that share a subtopic slug and getEntry("concepts",
    // `${domain}/${slug}`) works as documented in CONTRACT.md.
    generateId: ({ entry }) => entry.replace(/\.md$/, ""),
  }),
  schema: z.object({
    title: z.string(),
    domain: z.string(),
    slug: z.string(),
    /** group key: "all" | "core" | "advanced" | "aws". */
    group: z.string(),
    /** Approximate reading time (minutes), computed at sync from the body. */
    readingMinutes: z.number().int().positive(),
  }),
});

export const collections = { concepts };
